apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-flask
  template:
    metadata:
      labels:
        app: python-flask
    spec:
      containers:
      - image: docker.io/adsoft/python-flask:{github.sha}
        name: kafka-consumer
#        envFrom:
#        - configMapRef:
#            name: adsoftsito-config
#        livenessProbe:
#          httpGet:
#            path: /ht/
#            port: 8080
#          initialDelaySeconds: 5
#          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: python-flask
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "python-flask"
    port: 5000
  selector:
    app: python-flask
